server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yc?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 47.105.230.85 #服务器地址
    password: 135790 #密码
    database: 0     #数据库索引
    port: 6379  #端口
    jedis:
      pool:
        max-active:  8 #最大连接池数（负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（负值表示没有限制）
        max-idle: 8  #最大空闲连接
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.yzm.shop.DO
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.yzm.majoryc: debug
    org.springfromework.web: info